### PR TITLE
fix: graph layout, small layout tweaks

### LINKED ISSUE #173: [Safe{Pass}] Display of 0 boost in the graph
## Bug description
The 0 boost is weirdly wrapped in a tooltip, almost not visible.
Not critical, just an aesthetic change. 

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Connect to a Safe Accounts with 0 tokens
 2. Go to the Safe{Pass} app
 3. See the graph

## Expected result
Have a amrgin of at least 2px

## Screenshots
Screenshot 2024-04-26 at 13 27 20

### PR DESCRIPTION
**Pull request by schmanu**
Resolves #173 

## What this PR changes
- Shows tooltips on hover
- Fixes some margins / paddings
- Increases font size in graph

### CODE REVIEW

File: src/components/TokenLocking/BoostGraph/ArrowDownLabel.tsx [hunk 1]
```diff
@@ -6,6 +6,7 @@ export const ArrowDownLabel = ({ backgroundColor, ...props }: VictoryLabelProps
   if (props.x === undefined || props.y === undefined || props.text === '') {
     return null
   }
+  console.log(props)
```
Comment (katspaugh) [inline src/components/TokenLocking/BoostGraph/ArrowDownLabel.tsx:9]:
```suggestion
```

**Comment by schmanu** [comment]
> Does it fix #173?

Yes it fixes it :) It's a weird bug from the library.. Technically those labels are never 0, they sho 1.00x but only the 0 is shown.

**Review by jmealy — APPROVED** [review]
looks good
